// GENERATED CODE! Do not edit this file.

#include <stddef.h>

extern const char empty_wgsl[];
extern const size_t empty_wgsl_len;

const char empty_wgsl[] =
"";

const size_t empty_wgsl_len = sizeof(empty_wgsl) - 1;
