#!/usr/bin/env python3
# based on https://stackoverflow.com/a/46669656/19754926

import sys
import re
import os


def is_printable_ascii(byte):
    return byte >= ord(" ") and byte <= ord("~")


def needs_escaping(byte):
    return byte == ord('"') or byte == ord("\\")


def stringify_nibble(nibble):
    if nibble < 10:
        return chr(nibble + ord("0"))
    return chr(nibble - 10 + ord("a"))


def write_byte(of, byte):
    if is_printable_ascii(byte):
        if needs_escaping(byte):
            of.write("\\")
        of.write(chr(byte))
    elif byte == ord("\n"):
        of.write('\\n"\n"')
    else:
        of.write("\\x")
        of.write(stringify_nibble(byte >> 4))
        of.write(stringify_nibble(byte & 0xF))


def mk_valid_identifier(s):
    s = re.sub("^[^_a-z]", "_", s)
    s = re.sub("[^_a-z0-9]", "_", s)
    return s


def preprocess(shaderfile, shaderpath, included=set(), defines=dict()):
    if shaderfile in included:
        raise ValueError("Circular include for file: {shaderpath}")
    processed = []
    for line in shaderfile:
        line = line.strip()
        if line.startswith("#include"):
            include_file = line.split()[1].strip('"')
            include_path = os.path.join(os.path.dirname(shaderpath), include_file)
            if os.path.exists(include_path):
                processed.append(
                    preprocess(open(include_path, "r"), include_path, included)
                )
            else:
                raise FileNotFoundError(f"Included file not found: {include_file}")
        elif line.startswith("#define"):
            parts = line.split(maxsplit=2)
            if len(parts) == 3:
                symbol, value = parts[1], parts[2]
                defines[symbol] = value
            elif len(parts) == 2:
                symbol = parts[1]
                defines[symbol] = ""
            else:
                raise ValueError(f"Invalid #define directive: {line}")
        elif line.startswith("#ifdef"):
            symbol = line.split()[1]
            if symbol in defines:
                ifdef_block = []
                while True:
                    line = next(shaderfile).strip()
                    if line.startswith("#endif"):
                        processed.extend(ifdef_block)
                        break
                    elif line.startswith("#else"):
                        break
                    else:
                        ifdef_block.append(line)
            else:
                while True:
                    line = next(shaderfile).strip()
                    if line.startswith("#endif"):
                        break
                    elif line.startswith("#else"):
                        break
        elif line.startswith("#ifndef"):
            symbol = line.split()[1]
            if symbol not in defines:
                ifdef_block = []
                while True:
                    line = next(shaderfile).strip()
                    if line.startswith("#endif"):
                        processed.extend(ifdef_block)
                        break
                    elif line.startswith("#else"):
                        break
                    else:
                        ifdef_block.append(line)
            else:
                while True:
                    line = next(shaderfile).strip()
                    if line.startswith("#endif"):
                        break
                    elif line.startswith("#else"):
                        break
        else:
            for symbol, value in dict.items(defines):
                line = re.sub(rf"\b{symbol}\b", value, line)
            processed.append(line)

    return "\n".join(processed)


def main():
    # `xxd -i` compatibility
    if len(sys.argv) != 4 or sys.argv[1] != "-i":
        print("Usage: include_shader -i infile outfile")
        exit(2)

    with open(sys.argv[2], "r") as infile:
        with open(sys.argv[3], "w") as outfile:

            identifier = mk_valid_identifier(os.path.basename(sys.argv[2]))
            outfile.write("// GENERATED CODE! Do not edit this file.\n\n")
            outfile.write("#include <stddef.h>\n\n")
            outfile.write("extern const char {}[];\n".format(identifier))
            outfile.write("extern const size_t {}_len;\n\n".format(identifier))
            outfile.write('const char {}[] =\n"'.format(identifier))

            bytes = list(preprocess(infile, sys.argv[2]))

            for byte in bytes:
                if byte == b"":
                    break
                write_byte(outfile, ord(byte))

            outfile.write('";\n\n')
            outfile.write(
                "const size_t {}_len = sizeof({}) - 1;\n".format(identifier, identifier)
            )


if __name__ == "__main__":
    main()
